/**
 * Test: Fingerprint Spoofing Verification (Self-contained)
 * Reads the fingerprint.json generated by the app and verifies overrides in live browser.
 */
const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const PROFILE_DIR = path.join(process.env.APPDATA, 'pinterest-pin-publisher/local-data/profiles/YWNjOjE3ODI5MDI2MTQ2NjE');
const FP_PATH = path.join(PROFILE_DIR, 'fingerprint.json');

function ensureFingerprint() {
  if (fs.existsSync(FP_PATH)) return JSON.parse(fs.readFileSync(FP_PATH, 'utf-8'));
  const fp = {
    profileName: 'Win11-Chrome126-FHD',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
    platform: 'Win32', vendor: 'Google Inc.', oscpu: '',
    screenWidth: 1920, screenHeight: 1080, viewportWidth: 1903, viewportHeight: 969,
    colorDepth: 24, pixelRatio: 1, hardwareConcurrency: 8, deviceMemory: 8, maxTouchPoints: 0,
    language: 'en-US', languages: ['en-US', 'en'],
    timezoneId: 'America/New_York', timezoneOffset: 240,
    webglVendor: 'Google Inc. (NVIDIA)',
    webglRenderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)',
    connectionType: '4g', downlink: 10, rtt: 50,
    doNotTrack: null, cookieEnabled: true, pdfViewerEnabled: true,
    canvasNoiseSeed: parseInt(crypto.createHash('sha256').update(PROFILE_DIR + 'canvas').digest('hex').substring(0, 8), 16) % 100000,
    createdAt: new Date().toISOString(),
  };
  fs.writeFileSync(FP_PATH, JSON.stringify(fp, null, 2), 'utf-8');
  return fp;
}

function generateInjection(fp) {
  return `
    const navOvr = { platform:'${fp.platform}', vendor:'${fp.vendor}', hardwareConcurrency:${fp.hardwareConcurrency}, deviceMemory:${fp.deviceMemory}, maxTouchPoints:${fp.maxTouchPoints}, language:'${fp.language}', languages:${JSON.stringify(fp.languages)}, doNotTrack:${fp.doNotTrack ? `'${fp.doNotTrack}'` : 'null'}, cookieEnabled:${fp.cookieEnabled}, userAgent:'${fp.userAgent}' };
    for (const [p,v] of Object.entries(navOvr)) { try { Object.defineProperty(navigator,p,{get:()=>v,configurable:true}); } catch(e){} }
    const scrOvr = { width:${fp.screenWidth}, height:${fp.screenHeight}, availWidth:${fp.screenWidth}, availHeight:${fp.screenHeight-40}, colorDepth:${fp.colorDepth}, pixelDepth:${fp.colorDepth} };
    for (const [p,v] of Object.entries(scrOvr)) { try { Object.defineProperty(screen,p,{get:()=>v,configurable:true}); } catch(e){} }
    try { Object.defineProperty(window,'devicePixelRatio',{get:()=>${fp.pixelRatio},configurable:true}); } catch(e){}
    const origGP = WebGLRenderingContext.prototype.getParameter;
    WebGLRenderingContext.prototype.getParameter = function(p) { if(p===0x9245) return '${fp.webglVendor}'; if(p===0x9246) return '${fp.webglRenderer}'; return origGP.call(this,p); };
    if(typeof WebGL2RenderingContext!=='undefined'){const o2=WebGL2RenderingContext.prototype.getParameter;WebGL2RenderingContext.prototype.getParameter=function(p){if(p===0x9245)return'${fp.webglVendor}';if(p===0x9246)return'${fp.webglRenderer}';return o2.call(this,p);};}
    try{Object.defineProperty(navigator,'plugins',{get:()=>({length:5,0:{name:'PDF Viewer'},1:{name:'Chrome PDF Viewer'},2:{name:'Chromium PDF Viewer'},3:{name:'Microsoft Edge PDF Viewer'},4:{name:'WebKit built-in PDF'},item:function(i){return this[i]},namedItem:function(){return null},refresh:function(){},[Symbol.iterator]:function*(){for(let i=0;i<5;i++)yield this[i]}}),configurable:true});}catch(e){}
    try{delete navigator.__proto__.webdriver;Object.defineProperty(navigator,'webdriver',{get:()=>undefined,configurable:true});}catch(e){}
    try{delete window.__playwright;delete window.__pw_manual;}catch(e){}
  `;
}

async function main() {
  console.log('╔══════════════════════════════════════════╗');
  console.log('║  FINGERPRINT SPOOFING VERIFICATION TEST  ║');
  console.log('╚══════════════════════════════════════════╝\n');

  const fp = ensureFingerprint();
  console.log('Profile:  ' + fp.profileName);
  console.log('Platform: ' + fp.platform);
  console.log('Screen:   ' + fp.screenWidth + 'x' + fp.screenHeight + ' @' + fp.pixelRatio + 'x');
  console.log('CPU/RAM:  ' + fp.hardwareConcurrency + ' cores / ' + fp.deviceMemory + ' GB');
  console.log('Timezone: ' + fp.timezoneId);
  console.log('WebGL:    ' + fp.webglRenderer.substring(0, 50) + '...');
  console.log('');

  const context = await chromium.launchPersistentContext(PROFILE_DIR, {
    headless: false,
    userAgent: fp.userAgent,
    viewport: { width: fp.viewportWidth, height: fp.viewportHeight },
    locale: fp.language, timezoneId: fp.timezoneId,
    deviceScaleFactor: fp.pixelRatio,
    screen: { width: fp.screenWidth, height: fp.screenHeight },
    args: ['--start-maximized', '--disable-blink-features=AutomationControlled'],
  });
  await context.addInitScript(generateInjection(fp));

  const page = context.pages()[0] || await context.newPage();
  await page.goto('https://www.pinterest.com/', { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(3000);

  const r = await page.evaluate(() => {
    let wv='N/A',wr='N/A';
    try{const c=document.createElement('canvas');const gl=c.getContext('webgl');const ext=gl.getExtension('WEBGL_debug_renderer_info');if(ext){wv=gl.getParameter(ext.UNMASKED_VENDOR_WEBGL);wr=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL);}}catch(e){}
    return { ua:navigator.userAgent, pl:navigator.platform, hc:navigator.hardwareConcurrency, dm:navigator.deviceMemory, mt:navigator.maxTouchPoints, lang:navigator.language, dnt:navigator.doNotTrack, wd:navigator.webdriver, ce:navigator.cookieEnabled, sw:screen.width, sh:screen.height, cd:screen.colorDepth, dpr:window.devicePixelRatio, pc:navigator.plugins?.length, wv, wr };
  });

  let p=0, f=0;
  function chk(n,a,e){ const ok=JSON.stringify(a)===JSON.stringify(e); console.log((ok?'✅':'❌')+' '+n+': '+JSON.stringify(a)+(ok?'':' (want: '+JSON.stringify(e)+')')); if(ok)p++;else f++; }

  console.log('\n── Navigator ──');
  chk('platform', r.pl, fp.platform);
  chk('hardwareConcurrency', r.hc, fp.hardwareConcurrency);
  chk('deviceMemory', r.dm, fp.deviceMemory);
  chk('maxTouchPoints', r.mt, fp.maxTouchPoints);
  chk('language', r.lang, fp.language);
  chk('doNotTrack', r.dnt, fp.doNotTrack);
  chk('webdriver removed', r.wd, undefined);
  chk('cookieEnabled', r.ce, fp.cookieEnabled);
  chk('plugins count', r.pc, 5);

  console.log('\n── Screen ──');
  chk('screen.width', r.sw, fp.screenWidth);
  chk('screen.height', r.sh, fp.screenHeight);
  chk('colorDepth', r.cd, fp.colorDepth);
  chk('devicePixelRatio', r.dpr, fp.pixelRatio);

  console.log('\n── Identity ──');
  chk('userAgent', r.ua, fp.userAgent);

  console.log('\n── WebGL ──');
  chk('webglVendor', r.wv, fp.webglVendor);
  chk('webglRenderer', r.wr, fp.webglRenderer);

  console.log('\n' + '═'.repeat(40));
  console.log('✅ Passed: ' + p + '/' + (p+f));
  console.log('❌ Failed: ' + f + '/' + (p+f));

  await context.close();
  process.exit(f > 0 ? 1 : 0);
}
main().catch(e => { console.error('FATAL:', e); process.exit(1); });
